name = "chat-demo"
compatibility_date = "2025-08-09"

[build]
command = "npm install && npm run build"
cwd = ""

[build.environment]
NODE_VERSION = "18"

[[build.upload]]
format = "directory"
dir = "build"